<?php print_r($integrantes);?>
<table class='table table-hover table-bordered table-condensed'>
    <thead>
        <tr>
            <th>Rut</th>
            <th>Nombre</th>
            <th>Apellido</th>
            <th>Edad</th>
            <th>Cargo</th>
            <th>Grado</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>17390878-4</td>
            <td>Nicolás</td>
            <td>Fredes</td>
            <td>23</td>
            <td>Director</td>
            <td>Conquistador</td>
        </tr>
        <tr>
            <td>17390878-4</td>
            <td>Nicolás</td>
            <td>Fredes</td>
            <td>23</td>
            <td>Director</td>
            <td>Conquistador</td>
        </tr>
        <tr>
            <td>17390878-4</td>
            <td>Nicolás</td>
            <td>Fredes</td>
            <td>23</td>
            <td>Director</td>
            <td>Conquistador</td>
        </tr>
        <tr>
            <td>17390878-4</td>
            <td>Nicolás</td>
            <td>Fredes</td>
            <td>23</td>
            <td>Director</td>
            <td>Conquistador</td>
        </tr>
    </tbody>
</table>

<div class="clear"></div>